name: Publish Documentation Issues

on:
  workflow_dispatch:

jobs:
  publish-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Publish documentation issues using template
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python3 <<'EOF'
          import yaml
          import subprocess
          import re

          # Load project list
          with open('.github/project-list.yaml') as f:
              projects = yaml.safe_load(f)['projects']

          # Load template
          with open('.github/issue-template.yaml') as f:
              template = yaml.safe_load(f)

          def feature_name(project):
              return re.sub(r'^Rac\\.', '', project).lower()

          for project in projects:
              feature = feature_name(project)
              title = template['title'].replace('{project}', project)
              body = template['body'].replace('{project}', project).replace('{feature}', feature)
              labels = ','.join(template['labels'])
              cmd = ['gh', 'issue', 'create', '--title', title, '--body', body]
              if labels:
                  cmd += ['--label', labels]
              subprocess.run(cmd)
          EOF